services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logs:/logs
      - ./sincedb:/sincedb
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"